PORT_DATA EQU 3020H
PORT_MODE EQU 3021H

DATA SEGMENT
	STR1 DB "Self-Communication by 8251!"   
	COUNT EQU $-STR1
DATA ENDS

CODE SEGMENT 
	ASSUME DS:DATA, CS:CODE
START:	MOV AX, DATA
		MOV DS, AX
		CALL INIT
		CALL DELLY
		MOV AL, 01111110B  ;一个停止位， 偶校验， 字符长度位8位， 异步方式x16
		MOV DX, PORT_MODE
		OUT DX, AL  
		CALL DELLY
		MOV AL, 00110100B	;允许接收， 禁止发送
		OUT DX, AL
		CALL DELLY
		MOV CX, COUNT
		MOV SI, OFFSET STR1
A1:		MOV AX, 00110111B	;允许接收，允许发送
		MOV DX, PORT_MODE
		OUT DX, AL
		MOV AL, [SI]
		MOV DX, PORT_DATA
		OUT DX, AL
		MOV DX, PORT_MODE 
A2:		IN AL, DX
		AND AL, 01H		;发送端准备好
		JZ	A2
		CALL DELLY
A3:		IN AL, DX
		AND AL, 02H		;接收端准备好  
		JZ	A3
		MOV DX, PORT_DATA
		IN AL, DX
		MOV DL, AL
		MOV AH, 02H 
		INT 21H
		INC SI
		LOOP A1
A4:		MOV AH, 1
		INT 16H
		JZ A4
		MOV AX, 4C00H
		INT 21H
INIT	PROC
	MOV AL, 00H
	MOV DX, PORT_MODE
	OUT DX, AL 
	CALL DELLY
	OUT DX, AL
	CALL DELLY
	OUT DX, AL
	CALL DELLY
	MOV AL, 40H
	OUT DX, AL
	RET

DELLY	PROC
	PUSH CX
	MOV CX, 0003H
A5:	PUSH AX
	POP AX
	LOOP A5
	POP CX
	RET
	
CODE ENDS
	END START
	
		
		
		  
		