DATA	SEGMENT
	NUM DB 57H
	CHAR DB 2 DUP(0)
DATA ENDS
CODE	SEGMENT
	ASSUME CS:CODE, DS:DATA
START:	MOV AX, DATA
	MOV DS, AX
	MOV SI, OFFSET NUM
	MOV DI, OFFSET CHAR
	MOV DL, [SI]
	AND DL, 0F0H
	ROR DL, 4
	ADD DL, 30H
	MOV [DI], DL 
	INC DI
	MOV AH, 02H
	INT 21H
	MOV DL, [SI]
	AND DL, 0FH
	ADD DL, 30H
	MOV [DI], DL
	MOV AH, 02H
	INT 21H
	MOV AX, 4C00H
	INT 21H
CODE ENDS
	END START