DATA    SEGMENT
        BUFFER DW 3543H,5943H,-3578H,-3432H,4523H,3323H,-5634H,54EFH,-5423H,7230H  
        COUNT EQU ($-BUFFER)/2  
        RESULT DW 0, 0
DATA    ENDS

CODE    SEGMENT
        ASSUME CS:CODE,DS:DATA
START:  MOV AX, DATA
        MOV DS, AX
        MOV SI, OFFSET BUFFER  
        MOV DI, OFFSET RESULT
        MOV CX, COUNT  
        XOR AX, AX 
        XOR BX, BX 
AGAIN:	MOV DX, [SI]
		CMP DX, 0
		JLE NEXT 
		ADD AX, DX
		JC CARRY
		JMP NEXT  
CARRY:	INC BX		
NEXT:	INC SI
		INC SI
		LOOP AGAIN
		MOV [DI+2], AX
		MOV [DI], BX
        MOV AX, 4C00H
        INT 21H
CODE    ENDS
        END START