DATA    SEGMENT
        BUFFER DB 35H,32H,73H,10H,08H,0FH,2AH,3BH  
        COUNT EQU $-BUFFER 
        MAX DB 0  
        MIN DB 0
DATA    ENDS

CODE    SEGMENT
        ASSUME CS:CODE,DS:DATA
START:  MOV AX, DATA
        MOV DS, AX 
        ;TO FIND THE MAX
        MOV SI, OFFSET BUFFER
        MOV CX, COUNT 
        MOV AL, [SI]
AGAIN:	CMP AL, [SI]    
		JGE NEXT    
		MOV AL, [SI]
NEXT:	INC SI
		LOOP AGAIN   
		MOV MAX, AL  
		;TO FIND THE MIN
		MOV SI, OFFSET BUFFER
		MOV CX, COUNT
		MOV BL, [SI]
AGAIN2:	CMP BL, [SI]
		JLE NEXT2
		MOV BL, [SI]
NEXT2:	INC SI
		LOOP AGAIN2
		MOV MIN, BL
        MOV AX, 4C00H
        INT 21H
CODE    ENDS
        END START