DATA    SEGMENT
        BUFFER DB 34H,67H,0E2H,0A7H,89H,73H,51H,43H,0E2H,0A7H,89H,73H,67H,51H,43H,34H   
        COUNT EQU $-BUFFER 
DATA    ENDS

CODE    SEGMENT
        ASSUME CS:CODE,DS:DATA
START:  MOV AX, DATA
        MOV DS, AX 
       	MOV CX, COUNT-1
AGAIN: 	MOV SI, OFFSET BUFFER	
		MOV BX, CX
AGAIN2:	CMP BX, 0
		JLE NEXT 
		MOV AL, [SI]
		MOV DL, [SI+1]
		CMP AL, DL
		JA CHG
		JMP NEXT2
CHG:	MOV [SI], DL
		MOV [SI+1], AL
NEXT2:	DEC BX 
		INC SI
		JMP AGAIN2
NEXT:	LOOP AGAIN 
        MOV AX, 4C00H
        INT 21H
CODE    ENDS
        END START