PORT_0 EQU 3040H
PORT_C EQU 3043H 
DATA SEGMENT
	FREQ_LIST DW 441, 495, 556, 589, 661, 742, 833  
	COUNT EQU $-FREQ_LIST
	TIME_LIST DB 1, 1, 1, 1, 1, 1, 1
DATA ENDS

STACK1 SEGMENT
	DW 256 DUP(0)
STACK1 ENDS

CODE SEGMENT 
	ASSUME CS:CODE, DS:DATA
START:	MOV AX, DATA
		MOV DS, AX
		MOV SI, OFFSET FREQ_LIST 
		MOV DI, OFFSET TIME_LIST
		MOV DX, PORT_C
		MOV AL, 00110110B
		OUT DX, AL
        MOV CX, COUNT
AGAIN:	MOV DX, 0000H
		MOV AX, 4800H ;Ð¡µÄÆµÂÊ 18432hz = 4800h
		MOV BX, WORD PTR [SI]
		DIV WORD PTR [SI]
		MOV DX, PORT_0
		OUT DX, AL
		MOV AL, AH
		OUT DX, AL
		MOV DL, [DI]
		CALL DELAY
		ADD SI, 2
		INC DI
		CMP [SI], 
		LOOP AGAIN
		MOV AH, 1
		INT 16H
		JZ AGAIN
		MOV AX, 4C00H
		INT 21H
		
DELAY	PROC
D0:		MOV CX, 0F00H
D1:		MOV AX, 0FFFFH
D2:		DEC AX
		JNZ D2
		DEC CX
		JNZ D1
		DEC DL
		JNZ D0
		RET
DELAY	ENDP

CODE ENDS
		END START