DATA    SEGMENT
        BUFFER DB 10 DUP(0) 
        COUNT EQU ($-BUFFER) 
        RESULT DB 0
DATA    ENDS

CODE    SEGMENT
        ASSUME CS:CODE,DS:DATA
START:  MOV AX, DATA
        MOV DS, AX
        MOV SI, OFFSET BUFFER  
        MOV DI, OFFSET RESULT
        MOV CX, COUNT 
        ;INPUT 
AGAIN:	MOV AH, 01H
		INT 21H
		SUB AL, 30H
		MOV [SI], AL
		INC SI
		LOOP AGAIN
		;NEXT LINE 
		MOV AH, 02H
		MOV DL, 1AH
		INT 21H  
		;COMPUTE
        MOV SI, OFFSET BUFFER
        MOV CX, COUNT
        XOR AL, AL
AGAIN2:	ADD AL, [SI]
		DAA
		INC SI
		LOOP AGAIN2 
		;OUTPUT 
		MOV [DI], AL
		AND AL, 0F0H
		ROR AL, 4
		ADD AL, 30H
		MOV AH, 02H
		MOV DL, AL
		INT 21H
		MOV AL, [DI]
		AND AL, 0FH
		ADD AL, 30H
		MOV DL, AL
		INT 21H
		MOV AX, 4C00H
        INT 21H
CODE    ENDS
        END START