DATA    SEGMENT 
        STA DB 21H
        END DB 0FFH
DATA    ENDS

CODE    SEGMENT
        ASSUME CS:CODE,DS:DATA
START:  MOV AX, DATA
        MOV DS, AX
AGAIN2: MOV DL, STA 
        XOR CX, CX
        MOV CL, END
		SUB CL, STA
AGAIN:	MOV AH, 1
		INT 16H
		JNZ FINAL
		MOV AH, 02H
		INT 21H
		INC DL
		LOOP AGAIN
		JMP AGAIN2
FINAL:	MOV AX, 4C00H
        INT 21H
CODE    ENDS
        END START