DATA    SEGMENT 
		N DB 5
		RESULT DW 0
DATA    ENDS

CODE    SEGMENT 
MAIN	PROC FAR
        ASSUME CS:CODE,DS:DATA
START:  MOV AX, DATA
        MOV DS, AX 
        XOR CX, CX
        MOV CL, N
        MOV AX, 1
        CALL MMUL
        MOV RESULT, AX
		MOV AX, 4C00H
		INT 21H
MAIN	ENDP
        

MMUL	PROC FR
		PUSHF
AGAIN:	MUL CX
		LOOP AGAIN		
		POPF
		RET
MMUL	ENDP 

CODE	ENDS
		END MAIN