PUBLIC	INPUT1, INPUT2
EXTRN	ADD2	:FAR

DATA    SEGMENT 
		INPUT1 DB 11H, 22H
		INPUT2 DB 33H, 44H
DATA    ENDS

CODE    SEGMENT 
MAIN	PROC FAR
        ASSUME CS:CODE,DS:DATA
START:  MOV AX, DATA
        MOV DS, AX
        CALL ADD2
		MOV AX, 4C00H
		INT 21H
MAIN	ENDP